# postgresql
spring.datasource.url=jdbc:postgresql://dpg-da862g0n74is739ktau0-a.singapore-postgres.render.com/moneymanager_srinadh
spring.datasource.username=moneymanager_srinadh_user
spring.datasource.password=i7Bg86goTRDda6xpNgzWwX3CVp4dt4FT